"""Add chat sessions

Revision ID: d1b816889579
Revises: e4f7e66b3123
Create Date: 2026-08-11 17:33:55.307383
"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'd1b816889579'
down_revision: Union[str, None] = 'e4f7e66b3123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
