"""Add saved_products table

Revision ID: e4f7e66b3123
Revises: 306fe834c939
Create Date: 2026-08-11 13:02:12.377984
"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'e4f7e66b3123'
down_revision: Union[str, None] = '306fe834c939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
